<a href="https://colab.research.google.com/github/sarthakkad15/UCS420/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Build a simple Cognitive FAQ System using Pandas DataFrame.

In [3]:
import pandas as pd

In [4]:
roll_number = input("Enter your roll number: ")

print("Roll Number:", roll_number)
print("Last two digits:", roll_number[-2:])

Enter your roll number: 1024170117
Roll Number: 1024170117
Last two digits: 17

In [5]:
categories = ["billing", "account", "general"]

last_two_digits = [int(d) for d in roll_number[-2:]]

personalized_categories = [
    categories[d % 3] for d in last_two_digits
]

print("Last two digits:", last_two_digits)
print("Assigned categories:", personalized_categories)

Last two digits: [1, 7]
Assigned categories: ['account', 'account']

In [6]:
fixed_entries = [
    {
        "question": "what is the annual fee",
        "answer": "The annual fee is Rs 500.",
        "keywords": "fee cost price charge",
        "category": "billing"
    },
    {
        "question": "how to reset password",
        "answer": "Go to Settings > Reset Password.",
        "keywords": "password reset login",
        "category": "account"
    },
    {
        "question": "what are your working hours",
        "answer": "We are open 9 AM to 5 PM.",
        "keywords": "hours timing open time",
        "category": "general"
    },
    {
        "question": "how can i pay the fee",
        "answer": "You can pay via UPI, card, or net banking.",
        "keywords": "pay payment upi fee",
        "category": "billing"
    }
]

In [7]:
personalized_entries = []

for digit, category in zip(last_two_digits, personalized_categories):

    if category == "billing":
        question = "how can i check my recent payment"
        answer = "You can check your recent payment details from the billing section."
        keywords = "payment billing transaction"

    elif category == "account":
        question = "how do i update my registered mobile number"
        answer = "Go to Account Settings and update your registered mobile number."
        keywords = "mobile number update"

    else:
        question = "how can i contact customer support"
        answer = "You can contact customer support through the Help and Support section."
        keywords = "support help contact"

    personalized_entries.append({
        "question": question,
        "answer": answer,
        "keywords": keywords,
        "category": category
    })

personalized_entries

[{'question': 'how do i update my registered mobile number',
  'answer': 'Go to Account Settings and update your registered mobile number.',
  'keywords': 'mobile number update',
  'category': 'account'},
 {'question': 'how do i update my registered mobile number',
  'answer': 'Go to Account Settings and update your registered mobile number.',
  'keywords': 'mobile number update',
  'category': 'account'}]

In [8]:
all_entries = fixed_entries + personalized_entries

df = pd.DataFrame(all_entries)

print("Final FAQ DataFrame:")
display(df)

Final FAQ DataFrame:

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how do i update my registered mobile number,Go to Account Settings and update your registe...,mobile number update,account
5,how do i update my registered mobile number,Go to Account Settings and update your registe...,mobile number update,account

 2. Implement a scoring function that takes a query string and returns all matching entries ranked by confidence

In [9]:
def score_query(query, df):
    query_words = set(query.lower().split())

    results = []

    for index, row in df.iterrows():

        keywords = set(row["keywords"].lower().split())
        question_words = set(row["question"].lower().split())

        searchable_words = keywords.union(question_words)

        matched_words = query_words.intersection(searchable_words)

        score = len(matched_words) / len(query_words)

        if score > 0:
            results.append({
                "index": index,
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "confidence": score
            })

    results_df = pd.DataFrame(results)

    if not results_df.empty:
        results_df = results_df.sort_values(
            by="confidence",
            ascending=False
        ).reset_index(drop=True)

    return results_df

In [10]:
query = input("Enter your FAQ query: ")

results = score_query(query, df)

if results.empty:
    print("No matching FAQ found.")
else:
    print("\nMatching FAQs ranked by confidence:")
    display(results)

Enter your FAQ query: how to reset password

Matching FAQs ranked by confidence:

,index,question,answer,category,confidence
0,1,how to reset password,Go to Settings > Reset Password.,account,1.00
1,3,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,0.25
2,4,how do i update my registered mobile number,Go to Account Settings and update your registe...,account,0.25
3,5,how do i update my registered mobile number,Go to Account Settings and update your registe...,account,0.25

3. Write a function same_category(category_name, df) that returns all questions belonging to a given category.

In [11]:
def same_category(category_name, df):
    return df[df["category"] == category_name][["question", "category"]]

In [12]:
personalized_category = personalized_entries[0]["category"]

print("Selected personalized category:", personalized_category)

print("\nQuestions belonging to this category:")

display(
    same_category(personalized_category, df)
)

Selected personalized category: account

Questions belonging to this category:

                                      question category
1                        how to reset password  account
4  how do i update my registered mobile number  account
5  how do i update my registered mobile number  account

4. Pick any one entry in your knowledge base. Ask the user to input a new keyword, add it to that entry's keywords, and save your entire updated DataFrame to a CSV file named <your_roll_number>_faq_data.csv.

In [13]:
print("Current FAQ Knowledge Base:")

display(
    df[["question", "keywords", "category"]]
)

Current FAQ Knowledge Base:

,question,keywords,category
0,what is the annual fee,fee cost price charge,billing
1,how to reset password,password reset login,account
2,what are your working hours,hours timing open time,general
3,how can i pay the fee,pay payment upi fee,billing
4,how do i update my registered mobile number,mobile number update,account
5,how do i update my registered mobile number,mobile number update,account

In [14]:
entry_number = int(input("Enter the row number of the FAQ you want to update (0-5): "))

new_keyword = input("Enter a new keyword: ").strip().lower()

# Add keyword to existing keywords
df.loc[entry_number, "keywords"] = (
    df.loc[entry_number, "keywords"] + " " + new_keyword
)

print("\nUpdated FAQ entry:")
display(df.loc[[entry_number]])

Enter the row number of the FAQ you want to update (0-5): 3
Enter a new keyword: password

Updated FAQ entry:

,question,answer,keywords,category
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee password,billing

In [15]:
filename = f"{roll_number}_faq_data.csv"

df.to_csv(filename, index=False)

print(f"Updated DataFrame saved successfully as: {filename}")

Updated DataFrame saved successfully as: 1024170117_faq_data.csv

5.  Using groupby, print how many FAQ entries you have per category.

In [16]:
category_counts = df.groupby("category").size()

print("Number of FAQ entries per category:")
print(category_counts)

Number of FAQ entries per category:
category
account    3
billing    2
general    1
dtype: int64

In [17]:
category_counts_df = (
    df.groupby("category")
      .size()
      .reset_index(name="count")
)

display(category_counts_df)

  category  count
0  account      3
1  billing      2
2  general      1

6. Modify your Q2 scoring function so that if two or more entries tie for the highest score, it does not silently pick one — it prints all matching entries instead, so the user can see every equally good match

In [19]:
def score_query_with_tie(query, df):

    query_words = set(query.lower().split())

    results = []

    for index, row in df.iterrows():

        keywords = set(row["keywords"].lower().split())
        question_words = set(row["question"].lower().split())

        searchable_words = keywords.union(question_words)

        matched_words = query_words.intersection(searchable_words)

        score = len(matched_words) / len(query_words)

        if score > 0:
            results.append({
                "index": index,
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "confidence": score
            })

    results_df = pd.DataFrame(results)

    if results_df.empty:
        print("No matching FAQ found.")
        return results_df

    results_df = results_df.sort_values(
        by="confidence",
        ascending=False
    ).reset_index(drop=True)

    highest_score = results_df["confidence"].max()

    top_matches = results_df[
        results_df["confidence"] == highest_score
    ]

    print(f"Highest confidence score: {highest_score:.2f}")

    if len(top_matches) > 1:
        print("\nTIE DETECTED!")
        print("Multiple FAQs have the same highest confidence:")
    else:
        print("\nUnique highest-confidence match:")

    display(top_matches)

    return results_df

In [20]:
print(" TIE EXAMPLE ")

tie_results = score_query_with_tie("fee", df)

 TIE EXAMPLE
Highest confidence score: 1.00

TIE DETECTED!
Multiple FAQs have the same highest confidence:

,index,question,answer,category,confidence
0,0,what is the annual fee,The annual fee is Rs 500.,billing,1.0
1,3,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,1.0

In [21]:
print("NON-TIE EXAMPLE")

non_tie_results = score_query_with_tie(
    "password reset login",
    df
)

NON-TIE EXAMPLE
Highest confidence score: 1.00

Unique highest-confidence match:

,index,question,answer,category,confidence
0,1,how to reset password,Go to Settings > Reset Password.,account,1.0